#! /bin/bash

genSchema() {
  npx typescript-json-schema $2 $1 $NoExtraProps --required --skipLibCheck > tmp
}

gen() {
  echo Generating schema $1

  NoExtraProps="--noExtraProps"
  if [[ "$4" == "1" ]]; then
    NoExtraProps=""
  fi

  genSchema $1 $5
  echo -e "\
// This file is generated by /generate_schemas.sh in project root dir\n\
// After generating there might be missing nullable and type\n\
// attributes in some types, you need to add them manually\n\
import { JSONSchemaType } from \"ajv\"\n\
import { $1 } from \"../request_types\"\n\

$3 $(cat tmp) satisfies JSONSchemaType<$1>" > $6/$2.ts
  rm tmp
}


genRequestSchema() {
  gen $1 $2 "export default" $3 src/web_server/request_types.ts src/web_server/json_schema
}


# genRequestSchema ApiAnyReq api_any_req 1
# genRequestSchema TopUpNewFields top_up_new_req 0
# genRequestSchema TopUpGroupNewFields top_up_group_new_req 0
genRequestSchema TopUpGroupCreatePaymentFields top_up_group_create_payment_req 0
# genRequestSchema TopUpGroupConfirmPaymentFields top_up_group_confirm_payment_req  0
# genRequestSchema TopUpGroupAnyReq top_up_group_any_req  0
# genRequestSchema HistoryFields history_req 0


