// This file is generated by /generate_schemas.sh in project root dir
// After generating there might be missing nullable and type
// attributes in some types, you need to add them manually
import { JSONSchemaType } from "ajv"
import { ApiAnyReq } from "../request_types"

export default {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "action": {
            "type": "string"
        },
        "dataFields": {
            "additionalProperties": true,
            "properties": {},
            "type": "object",
            nullable: true
        },
        "fields": {
            "additionalProperties": true,
            "properties": {},
            "type": "object",
            nullable: true
        },
        "sessionFields": {
            "additionalProperties": true,
            "properties": {},
            "type": "object",
            nullable: true
        }
    },
    "required": [
        "action"
    ],
    "type": "object"
} satisfies JSONSchemaType<ApiAnyReq>
