// This file is generated by /generate_schemas.sh in project root dir
// After generating there might be missing nullable and type
// attributes in some types, you need to add them manually
import { JSONSchemaType } from "ajv"
import { ApiEkassaCheckTokenReq } from "../request_types"

export default {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
        "action": {
            "const": "CheckToken",
            "type": "string"
        },
        "fields": {
            "additionalProperties": false,
            "properties": {
                "token": {
                    "type": "string"
                }
            },
            "required": [
                "token"
            ],
            "type": "object"
        }
    },
    "required": [
        "action",
        "fields"
    ],
    "type": "object"
} satisfies JSONSchemaType<ApiEkassaCheckTokenReq>
