// This file is generated by /generate_schemas.sh in project root dir
// After generating there might be missing nullable and type
// attributes in some types, you need to add them manually
import { JSONSchemaType } from "ajv"
import { ApiEkassaGetBalanceReq } from "../request_types"

export default {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
        "TopUpServiceType": {
            "enum": [
                "cdma",
                "inet",
                "iptv",
                "phone"
            ],
            "type": "string"
        }
    },
    "properties": {
        "action": {
            "const": "GetBalance",
            "type": "string"
        },
        "fields": {
            "additionalProperties": false,
            "properties": {
                "phoneNumber": {
                    "type": "string"
                },
                "serviceCode": {
                    "$ref": "#/definitions/TopUpServiceType"
                }
            },
            "required": [
                "phoneNumber",
                "serviceCode"
            ],
            "type": "object"
        }
    },
    "required": [
        "action",
        "fields"
    ],
    "type": "object"
} satisfies JSONSchemaType<ApiEkassaGetBalanceReq>
