// This file is generated by /generate_schemas.sh in project root dir
// After generating there might be missing nullable and type
// attributes in some types, you need to add them manually
import { JSONSchemaType } from "ajv"
import { ApiHistoryRequest } from "../request_types"

export default {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
        "action": {
            "const": "List",
            "type": "string"
        },
        "fields": {
            "additionalProperties": false,
            "properties": {
                "maxDate": {
                    "type": "string",
                    nullable: true
                },
                "minDate": {
                    "type": "string",
                    nullable: true
                },
                "phoneNumber": {
                    "type": "string"
                },
                "skip": {
                    "type": "number",
                    nullable: true
                },
                "take": {
                    "type": "number",
                    nullable: true
                }
            },
            "required": [
                "phoneNumber"
            ],
            "type": "object"
        }
    },
    "required": [
        "action",
        "fields"
    ],
    "type": "object"
} satisfies JSONSchemaType<ApiHistoryRequest>
