// This file is generated by /generate_schemas.sh in project root dir
// After generating there might be missing nullable and type
// attributes in some types, you need to add them manually
import { JSONSchemaType } from "ajv"
import { TopUpNewFields } from "../request_types"

export default {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
        "TopUpServiceType": {
            "enum": [
                "inet",
                "iptv",
                "phone",
                "cdma"
            ],
            "type": "string"
        }
    },
    "properties": {
        "action": {
            "const": "New",
            "type": "string"
        },
        "fields": {
            "additionalProperties": false,
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "phoneNumber": {
                    "type": "string",
                    pattern: "^\\+?\\d+$"
                },
                "pluginInfoName": {
                    "type": "string"
                },
                "serviceType": {
                    "$ref": "#/definitions/TopUpServiceType"
                },
                "topUpGroupId": {
                    "type": "number"
                }
            },
            "required": [
                "amount",
                "phoneNumber",
                "pluginInfoName",
                "serviceType",
                "topUpGroupId"
            ],
            "type": "object"
        },
        "dataFields": {
            "additionalProperties": true,
            "properties": {
                "description": {
                    "type": "string",
                    nullable: true
                }
            },
            nullable: true,
            type: "object"
        }
    },
    "required": [
        "action",
        "fields"
    ],
    "type": "object"
} satisfies JSONSchemaType<TopUpNewFields>
