// This file is generated by /generate_schemas.sh in project root dir
// After generating there might be missing nullable and type
// attributes in some types, you need to add them manually
import { JSONSchemaType } from "ajv"
import { TopUpGroupCreatePaymentFields } from "../request_types"

export default {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
        "action": {
            "const": "CreatePayment",
            "type": "string"
        },
        "fields": {
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "number"
                }
            },
            "required": [
                "id"
            ],
            "type": "object"
        },
        "sessionFields": {
            "additionalProperties": false,
            "properties": {
                "bankPluginInfoName": {
                    "type": "string"
                },
                "card.cvc": {
                    "type": "string",
                    pattern: "^\\d+$"
                },
                "card.holder": {
                    "type": "string"
                },
                "card.month": {
                    "type": "string",
                    pattern: "^0?(1|2|3|4|5|6|7|8|9|(10)|(11)|(12))$"
                },
                "card.pan": {
                    "type": "string",
                    pattern: "^\\d{16}$"
                },
                "card.year": {
                    "type": "string",
                    pattern: "^\\d{2}$"
                },
                "vendorName": {
                    "type": "string"
                }
            },
            "required": [
                "bankPluginInfoName",
                // "card.cvc",
                "card.holder",
                "card.month",
                "card.pan",
                "card.year",
                "vendorName"
            ],
            "type": "object"
        }
    },
    "required": [
        "action",
        "fields",
        "sessionFields"
    ],
    "type": "object"
} satisfies JSONSchemaType<TopUpGroupCreatePaymentFields>
