// This file is generated by /generate_schemas.sh in project root dir
// After generating there might be missing nullable and type
// attributes in some types, you need to add them manually
import { JSONSchemaType } from "ajv"
import { TopUpGroupConfirmPaymentFields } from "../request_types"

export default {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
        "action": {
            "const": "ConfirmPayment",
            "type": "string"
        },
        "fields": {
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "number"
                }
            },
            "required": [
                "id"
            ],
            "type": "object"
        },
        "sessionFields": {
            "additionalProperties": false,
            "properties": {
                "otpCode": {
                    "type": "string",
                    pattern: "^\\d{1,10}$"
                }
            },
            "required": [
                "otpCode"
            ],
            "type": "object"
        }
    },
    "required": [
        "action",
        "fields",
        "sessionFields"
    ],
    "type": "object"
} satisfies JSONSchemaType<TopUpGroupConfirmPaymentFields>
