// This file is generated by /generate_schemas.sh in project root dir
// After generating there might be missing nullable and type
// attributes in some types, you need to add them manually
import { JSONSchemaType } from "ajv"
import { TopUpGroupNewFields } from "../request_types"

export default {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
        "action": {
            "const": "New",
            "type": "string"
        },
        "fields": {
            "additionalProperties": false,
            "properties": {
                "liteUserId": {
                    "type": "integer",
                },
                "amount": {
                    "type": "integer"
                },
                "phoneNumber": {
                    "type": "string",
                    pattern: "^\\+?\\d+$"
                }
            },
            "required": [
                "amount",
                "phoneNumber"
            ],
            "type": "object"
        },
        "dataFields": {
            "additionalProperties": true,
            "properties": {
                "description": {
                    "type": "string",
                    nullable: true
                }
            },
            nullable: true,
            type: "object"
        }
    },
    "required": [
        "action",
        "fields"
    ],
    "type": "object"
} satisfies JSONSchemaType<TopUpGroupNewFields>
